# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  name: "BusinessTools On-Prem Documentation"

steps:
- checkout: self
  clean: true
  submodules: true
  
- task: DeleteFiles@1
  inputs:
    SourceFolder: 
    Contents: |
      package-lock.json
      yarn.lock

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.21.1'
- task: Yarn@3
  inputs:
    arguments: 'install'
- task: CmdLine@2
  inputs:
    script: 'npm install'
# get the Reveal repo
- task: CmdLine@2
  inputs:
    script: 'git submodule update --init --recursive'
# copy Reveal md files to Slingshot files folder
- task: CopyFiles@2
  inputs:
    sourceFolder: reveal-docs\en
    Contents: |
      **\*
      !**\toc.yml
    targetFolder: docTopics\en\components\analytics
    overWrite: true
# copy Reveal toc files to Slingshot files folder
- task: CopyFiles@2
  inputs:
    sourceFolder: reveal-images\en
    Contents: '**\toc.yml'
    targetFolder: docfx\en\components\analytics
    overWrite: true
# copy Reveal images and md files to Slingshot files folder
- task: CopyFiles@2
  inputs:
    sourceFolder: reveal-images\en
    Contents: |
      **\*.png
      **\*.md
    targetFolder: docTopics\en\components\analytics
    overWrite: true
# Install the image compression tool
- task: CmdLine@2
  inputs: 
    script: 'npm i -g @funboxteam/optimizt'
# Run the image compression tool on Slingshot images
- task: CmdLine@2
  inputs: 
    workingDirectory: doctopics\en\images
    script: 'optimizt --lossless doctopics\en\images'
# Run the image compression tool on Reveal images
- task: PowerShell@2
  inputs: 
    script: Get-ChildItem -Recurse -Filter *.png | Foreach-Object { optimizt --lossless $_.FullName }
    targetType: 'inline'
    workingDirectory: reveal-docs\en
# Update the hrefs in Reveal md files
- task: RegexReplace@3
  inputs:
    InputSearchPattern: 'docTopics\en\components\analytics\**\*.md'
    FindRegex: '~\/en\/'
    ReplaceRegex: '~/components/analytics/'
    UseUTF8: false
    UseRAW: true
# Update the download links in Reveal md files
- task: RegexReplace@3
  inputs:
    InputSearchPattern: 'docTopics\en\components\analytics\**\*.md'
    FindRegex: 'http:\/\/download\.infragistics\.com\/(reportplus|reveal)\/'
    ReplaceRegex: 'https://download.infragistics.com/slingshot/'
    UseUTF8: false
    UseRAW: true
# Update the Dashboard/Visualization Tutorials links in Reveal md files
- task: RegexReplace@3
  inputs:
    InputSearchPattern: 'docTopics\en\components\analytics\**\*.md'
    FindRegex: 'http:\/\/download\.infragistics\.com\/(reportplus|reveal)\/help\/samples\/Reveal'
    ReplaceRegex: 'https://download.infragistics.com/slingshot/samples/Slingshot'
    UseUTF8: false
    UseRAW: true
# Update the Dataset links in Reveal md files
- task: RegexReplace@3
  inputs:
    InputSearchPattern: 'docTopics\en\components\analytics\**\*.md'
    FindRegex: 'http:\/\/download\.infragistics\.com\/(reportplus|reveal)\/help\/samples\/HR\%20Dataset_2016'
    ReplaceRegex: 'https://download.infragistics.com/slingshot/samples/HR_Dataset_2016'
    UseUTF8: false
    UseRAW: true
# Update the Retail Store links in Reveal md files
- task: RegexReplace@3
  inputs:
    InputSearchPattern: 'docTopics\en\components\analytics\**\*.md'
    FindRegex: 'http:\/\/download\.infragistics\.com\/(reportplus|reveal)\/help\/samples\/Retail_Store'
    ReplaceRegex: 'https://download.infragistics.com/slingshot/samples/Retail-Store'
    UseUTF8: false
    UseRAW: true
# Replace 'Reveal' with 'Analytics' in all .md files
- task: RegexReplace@3
  inputs:
    InputSearchPattern: 'docTopics\en\components\analytics\**\*.md'
    FindRegex: 'Reveal'
    ReplaceRegex: 'Analytics'
    UseUTF8: false
    UseRAW: true
- task: Yarn@3
  inputs:
    arguments: 'build build-docfx-Slingshot'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/Slingshot'
    ArtifactName: 'docs'
    publishLocation: 'FilePath'
    TargetPath: '\\igbgsofsmb2\builds\Slingshot\Docs\$(Build.DefinitionName)\$(Build.BuildNumber)'
    Parallel: true