# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  name: "BusinessTools On-Prem Documentation"

steps:
- checkout: self
  clean: true
  submodules: true
  
- task: DeleteFiles@1
  inputs:
    SourceFolder: 
    Contents: |
      package-lock.json
      yarn.lock

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.21.1'
- task: Yarn@3
  inputs:
    arguments: 'install'
- task: CmdLine@2
  inputs:
    script: 'npm install'
# get the Reveal repo
- task: CmdLine@2
  inputs:
    script: 'git submodule update --init --recursive'
# Replace 'Reveal' with 'Dashboards' in all .md files
- task: RegexReplace@3
  inputs:
    InputSearchPattern: 'reveal-docs\en\**\*.md'
    FindRegex: 'Reveal'
    ReplaceRegex: 'Dashboards'
    UseUTF8: false
    UseRAW: true
# copy Reveal md files to Slingshot files folder
- task: CopyFiles@2
  inputs:
    sourceFolder: reveal-docs\en
    Contents: |
      **\*
      !**\toc.yml
    targetFolder: docTopics\en\components\Reveal
    overWrite: true
# copy Reveal toc files to Slingshot files folder
- task: CopyFiles@2
  inputs:
    sourceFolder: reveal-docs\en
    Contents: '**\toc.yml'
    targetFolder: docfx\en\components\Reveal
    overWrite: true
- task: Yarn@3
  inputs:
    arguments: 'build build-docfx-Slingshot'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/Slingshot'
    ArtifactName: 'docs'
    publishLocation: 'FilePath'
    TargetPath: '\\igbgsofsmb2\builds\Slingshot\Docs\$(Build.DefinitionName)\$(Build.BuildNumber)'
    Parallel: true